* `nse.py` programs   
* [x] Get NSE symbols   
* [x] Build option chains   
* [x] Get accurate dte
* [x] Get prices   
* [ ] Get margins

## Get nse symbols

In [20]:
# hack to change jupyter directory in notebooks for imports
import os
from pathlib import Path
if Path.cwd().parts[-1] == 'notebooks':
    root = Path.cwd().parent
else:
    root = Path.cwd()
os.chdir(root)

# Logger
import logging, logging.config
import yaml

with open(root / 'config' / 'log.yml', 'r') as f:
    config = yaml.safe_load(f.read())
    logging.config.dictConfig(config)

log = logging.getLogger('ib_log')

# lets have a look at the overall goals
from IPython.core.display import SVG
SVG(root / 'docs' / '_overview.svg')

# Function in nse/nse/get_nse_syms()
import requests
import pandas as pd
import numpy as np
from io import StringIO

def get_nse_syms() -> pd.DataFrame:
    """Generates symbols for nse with expiry months having lots"""

    url = "https://www1.nseindia.com/content/fo/fo_mktlots.csv"

    try:
        req = requests.get(url)
        if req.status_code == 404:
            print(f"\n{url} URL contents not correct. 404 error!")
        df_syms = pd.read_csv(StringIO(req.text))
    except requests.ConnectionError as e:
        print(f"Connection Error {e}")
    except pd.errors.ParserError as e:
        print(f"Parser Error {e}")

    df_syms = df_syms[list(df_syms)[1:5]] 

    # strip whitespace from columns and make it lower case
    df_syms.columns = df_syms.columns.str.strip().str.lower()

    # strip all string contents of whitespaces
    df_syms = df_syms.applymap(lambda x: x.strip()
                                        if type(x) is str else x)

    # remove 'Symbol' row
    df_syms = df_syms[df_syms.symbol != "Symbol"]

    # introduce `secType`
    df_syms.insert(1, 'secType', np.where(df_syms.symbol.str.contains('NIFTY'), 'IND', 'STK'))

    # introduce `exchange`
    df_syms.insert(2, 'exchange', 'NSE')

    # introduce `currency`
    df_syms.insert(3, 'currency', 'INR')

    return df_syms

In [2]:
# get the symbols
from src.nse.nse import get_nse_syms
df_syms = get_nse_syms()
df_syms.head(5)

       symbol secType exchange mar-23 apr-23 may-23
0  MIDCPNIFTY     IND      NSE     75     75     75
1    FINNIFTY     IND      NSE     40     40     40
2   BANKNIFTY     IND      NSE     25     25     25
3     NIFTY50     IND      NSE     50     50     50
5   ABCAPITAL     STK      NSE   5400   5400   5400

# Build Option Chains

# Function in src/nse/nse/get_nse_chain()

symbol = 'NIFTY'

from nsepython import nse_optionchain_scrapper, nse_get_fno_lot_sizes
import pandas as pd

# prevent urllib DEBUG connectionpool logs from nsepython requests
logging.getLogger('urllib3').setLevel(logging.WARNING) 


def get_nse_chain(symbol: str) -> pd.DataFrame:
        """Get Option Chains for a symbol"""

        scraped = nse_optionchain_scrapper(symbol)

        raw_dict = scraped['records']['data']
        dfs = [pd.DataFrame.from_dict(raw_dict[i]).transpose()[2:] 
                for i in range(len(raw_dict))]

        df = pd.concat(dfs).drop(columns='identifier').rename_axis('right').reset_index()

        float_cols = ['strikePrice', 'pchangeinOpenInterest', 'impliedVolatility', 
                'lastPrice', 'change', 'pChange', 'bidprice', 'askPrice' , 
                'underlyingValue' ]
        int_cols = ['openInterest', 'changeinOpenInterest', 'totalTradedVolume', 
                'totalBuyQuantity', 'totalSellQuantity', 'bidQty', 'askQty']
        df[float_cols] = df[float_cols].astype('float32')
        df[int_cols] = df[int_cols].astype('int64')
        df['expiryDate'] = pd.to_datetime(df.expiryDate)

        colmap = { 'underlying': 'symbol', 'expiryDate': 'expiry', 'strikePrice': 'strike',  
                'right': 'right','underlyingValue': 'undPrice', 'openInterest': 'oi',
                'changeinOpenInterest': 'oiChange', 'pchangeinOpenInterest': 'pChangeOI',
                'totalTradedVolume': 'volume', 'totalBuyQuantity': 'totalBuyQty', 
                'totalSellQuantity': 'totalSellQty', 'pChange': 'pChange', 
                'impliedVolatility': 'opt_iv',   'lastPrice': 'lastPrice', 'change': 'change',
                'bidQty': 'bidQty', 'bidprice': 'bid', 'askPrice': 'ask', 'askQty': 'askQty',
                }

        df = df.rename(columns=colmap)[colmap.values()]
        df = df.assign(lot=nse_get_fno_lot_sizes(symbol=symbol))
        df = df.assign(opt_iv = df.opt_iv/100)
        df = df.assign(right=df.right.str[:1])
        df = df.sort_values(['expiry', 'right', 'strike'], 
                        ascending=[True, False, True]).reset_index(drop=True)

        return df

# Moved to src\generate.py

# Gets new chains if they are old

from pathlib import Path

import pandas as pd
from tqdm.notebook import tqdm_notebook

from src.nse.nse import get_nse_chain
from src.support import pickle_age

days_old = 0.75 # set how many days old
chains_file = root / 'data' / 'master'

try:
    chain_age_delta = pickle_age(chains_file)['nse_chains.pkl']
    chain_age = chain_age_delta.days + chain_age_delta.hours/24 + chain_age_delta.minutes/24/60
except KeyError:
    chain_age = days_old + 1 # force regeneration

old_chains = chain_age > days_old
dfs = []

if old_chains:
    tq_scrips = tqdm_notebook(df_syms.symbol, bar_format="{desc:<8}{percentage:3.0f}%{r_bar}")
    for s in tq_scrips:
        tq_scrips.set_description(f"{s}")
        try:
            dfs.append(get_nse_chain(s))
        except KeyError as e:
            log.error(f"{s} has error {e}")
    # dfs = [get_nse_chain(s) for s in ] # regenerate
else:
    dfs = [pd.read_pickle(chains_file / 'nse_chains.pkl')]

# assemble the chains
nse_chains = pd.concat(dfs,ignore_index=True)

# store the nse_chains if new
if old_chains:
    data_path = root / 'data' / 'master' / 'nse_chains.pkl'
    nse_chains.to_pickle(data_path)

# Get accurate dte

# Function in /support/get_dte()

import pytz
import datetime
from typing import Union

x = datetime.datetime(2023, 5, 13) # x is to be converted to mkt close
exchange = 'nse'

tz_dict = {'nse': ('Asia/Kolkata', 18), 'snp': ('EST', 16)}
tz, hr = tz_dict[exchange.lower()]

mkt_tz = pytz.timezone(tz)
mkt_close_time = datetime.time(hr, 0)

now = datetime.datetime.now(tz=mkt_tz)

mkt_close = datetime.datetime.combine(x.date(), mkt_close_time).astimezone(mkt_tz)

dte = (mkt_close-now).total_seconds()/24/3600

# Moved to src\generate.py

# get the dtes for the chains
from src.support import get_dte

exchange = df_syms.exchange.iloc[0]

dte = nse_chains.expiry.apply(lambda x: get_dte(x, exchange))
dte.name = 'dte'

# insert the dtes
try:
    nse_chains.insert(5, 'dte', dte)
except ValueError:
    log.warning('dte already in nse_chains, will be refreshed')
    nse_chains = nse_chains.assign(dte=dte)

# Get prices of underlyings

# Function in src/nse/nse/get_prices

def get_prices() -> pd.DataFrame:
    """Get the underlying prices"""

    df_eq = equity_prices()
    df_ix = index_prices()

    df = pd.concat([df_eq, df_ix], ignore_index=True)
    ltp = df['last'].combine_first(df.ltP)
    df = df.assign(last=ltp, ltP=ltp)

    # harmonize time to time value
    df.timeVal = pd.to_datetime(df.timeVal).dt.tz_localize('Asia/Calcutta')
    df.timeVal = df.timeVal.max()

    return df

import pandas as pd
from src.nse.nse import equity_prices, index_prices

df_eq = equity_prices()
df_ix = index_prices()

df = pd.concat([df_eq, df_ix], ignore_index=True)
ltp = df['last'].combine_first(df.ltP)
df = df.assign(last=ltp, ltP=ltp)

# harmonize time to time value
df.timeVal = pd.to_datetime(df.timeVal).dt.tz_localize('Asia/Calcutta')
df.timeVal = df.timeVal.max()

In [3]:
from src.nse.nse import get_prices
nse_prices = get_prices()
nse_prices.head()

,symbol,open,high,low,ltP,ptsC,per,trdVol,trdVolM,ntP,...,yearLow,last,indexName,yearHigh,previousClose,indexType,timeVal,percChange,indexOrder,indexSubType
0,PVR,"1,504.95","1,535.75","1,494.80","1,530.00",32.95,2.20,4.29,0.43,65.20,...,NaN,"1,530.00",NaN,NaN,NaN,NaN,2023-03-14 15:33:07+05:30,NaN,NaN,NaN
1,ZEEL,187.20,193.90,187.10,192.30,4.00,2.12,65.11,6.51,124.73,...,NaN,192.30,NaN,NaN,NaN,NaN,2023-03-14 15:33:07+05:30,NaN,NaN,NaN
2,TRENT,"1,331.10","1,351.00","1,296.95","1,351.00",26.90,2.03,6.27,0.63,83.17,...,NaN,"1,351.00",NaN,NaN,NaN,NaN,2023-03-14 15:33:07+05:30,NaN,NaN,NaN
3,MCDOWELL-N,757.15,770.55,756.10,768.80,14.40,1.91,20.25,2.03,154.75,...,NaN,768.80,NaN,NaN,NaN,NaN,2023-03-14 15:33:07+05:30,NaN,NaN,NaN
4,M&MFIN,237.00,244.70,237.00,242.90,4.40,1.84,35.24,3.52,85.09,...,NaN,242.90,NaN,NaN,NaN,NaN,2023-03-14 15:33:07+05:30,NaN,NaN,NaN

# Get the margins

In [19]:
from src.nse.nse import get_nse_syms
get_nse_syms()

         symbol secType exchange mar-23 apr-23 may-23
0    MIDCPNIFTY     IND      NSE     75     75     75
1      FINNIFTY     IND      NSE     40     40     40
2     BANKNIFTY     IND      NSE     25     25     25
3       NIFTY50     IND      NSE     50     50     50
5     ABCAPITAL     STK      NSE   5400   5400   5400
..          ...     ...      ...    ...    ...    ...
191      RECLTD     STK      NSE   8000   8000   8000
192         UPL     STK      NSE   1300   1300   1300
193  ULTRACEMCO     STK      NSE    100    100    100
194         TCS     STK      NSE    175    175    175
195  TORNTPOWER     STK      NSE   1500

[195 rows x 6 columns]

# Checkout nse_index and df_syms for MIDCPNIFTY

In [24]:
from src.nse.nse import get_nse_syms

In [33]:
df_syms = get_nse_syms()

In [30]:
df_syms.symbol.str.match(searchfor)

TypeError: unhashable type: 'list'